config/routes.rb
Rails.application.routes.draw do
  root "staticpages#home", to: "staticpages#home"
  get "staticpages/:page", to: "staticpages#show"
  post "/signup", to: "users#create"
  get "/signup", to: "users#new"
  resources :users
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments
  end

  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def show
    render template: "staticpages/#{params[:page]}"
  end

  def home
    if logged_in?
      @post = current_user.posts.build
      @feed_items = Post.feed(current_user.id).paginate page: params[:page],
        per_page: Settings.users.per_page
    end
  end
end

app/views/staticpages/home.html.erb
<% provide :title, t(".title") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="post_form">
        <%= render "shared/post_form" %>
      </section>
      <section class="post_form">
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t ".post_feed" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t ".welcome" %></h1>
    <h2>
      <%= t ".h2" %>
      <%= link_to t(".rails"), "http://www.railstutorial.org/" %>
      <%= t ".sample" %>
    </h2>

    <%= link_to t(".sigup"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>