config/routes.rb
Rails.application.routes.draw do
  root "staticpages#home", to: "staticpages#home"
  get "staticpages/:page", to: "staticpages#show"
  post "/signup", to: "users#create"
  get "/signup", to: "users#new"
  resources :users
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments
  end

  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_comment_form.html.erb
<div style="margin-left: 40px;">
    <section class="post_form">
      <%= render post.comments %>
    </section>
    <%= link_to gravatar_for(current_user, size: 20), current_user %>
    <span style="font-size: 12px;"><%= link_to current_user.name, post.user %></span>
    <%= form_for [post, post.comments.build], remote: true do |f| %>
    <span class="timestamp">
      <%= f.text_field :content, class: "form-control" %>
      <%= f.submit "comment", class: "btn btn-primary" %>
    </span>
    <%end%>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form_contains" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <h3><%= t ".title" %></h3>
    <%= f.text_field :title, class: "form-control" %>
    <%= f.text_area :content, placeholder: t(".create_new_post") %>
  </div>
  <%= f.submit t(".post"), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".view_my_profile"), current_user %></span>
<span><%= pluralize current_user.posts.count, t(".post") %></span>